import type { EncounterPhase, EnemyRoleDefinition } from './types';

export const ENEMY_ROLES: Record<string, EnemyRoleDefinition> = {
  scout: {
    role: 'scout',
    label: 'Scout',
    color: 0xc77dff,
    radius: 9,
    maxHealth: 24,
    attackDamage: 6,
    attackRange: 38,
    attackCooldown: 700,
    speed: 145,
    forcesDecision: 'Pull companion back to protect Commander, or keep pressuring?',
  },
  archer: {
    role: 'archer',
    label: 'Archer',
    color: 0xff8c42,
    radius: 10,
    maxHealth: 28,
    attackDamage: 10,
    attackRange: 220,
    attackCooldown: 1400,
    speed: 75,
    forcesDecision: 'Close distance, reposition, or designate Archer as priority?',
  },
  bruiser: {
    role: 'bruiser',
    label: 'Bruiser',
    color: 0x9d0208,
    radius: 20,
    maxHealth: 120,
    attackDamage: 14,
    attackRange: 48,
    attackCooldown: 1200,
    speed: 55,
    forcesDecision: 'Focus fire the Bruiser, or ignore it and risk losing formation?',
  },
  support: {
    role: 'support',
    label: 'Support',
    color: 0x52b788,
    radius: 11,
    maxHealth: 32,
    attackDamage: 0,
    attackRange: 0,
    attackCooldown: 0,
    speed: 65,
    forcesDecision: 'Eliminate Support immediately, even if it exposes the Commander?',
  },
  assassin: {
    role: 'assassin',
    label: 'Assassin',
    color: 0x7209b7,
    radius: 10,
    maxHealth: 30,
    attackDamage: 16,
    attackRange: 40,
    attackCooldown: 800,
    speed: 100,
    forcesDecision: 'Intercept with companion, reposition, or sacrifice offensive pressure?',
  },
  siege: {
    role: 'siege',
    label: 'Siege',
    color: 0x6c757d,
    radius: 16,
    maxHealth: 70,
    attackDamage: 18,
    attackRange: 280,
    attackCooldown: 2200,
    speed: 40,
    forcesDecision: 'Defend command position, relocate, or eliminate the Siege Unit?',
  },
  boss: {
    role: 'boss',
    label: 'Field Captain',
    color: 0x6a040f,
    radius: 26,
    maxHealth: 380,
    attackDamage: 12,
    attackRange: 55,
    attackCooldown: 1500,
    speed: 50,
    forcesDecision: 'Full command test',
  },
};

export const ENEMY_AI = {
  archerPreferredMinRange: 160,
  archerPreferredMaxRange: 260,
  archerFleeRange: 95,
  supportBuffRadius: 110,
  supportBuffSpeedMultiplier: 1.25,
  supportHealRadius: 120,
  supportHealAmount: 12,
  supportHealIntervalMs: 1800,
  supportFleeRange: 115,
  scoutFlankOffset: 90,
  scoutIsolationRadius: 130,
  scoutAllyCountToHold: 1,
  scoutEvasiveRange: 70,
  bruiserKnockbackForce: 180,
  bruiserGuardRadius: 200,
  assassinStalkRange: 200,
  assassinOpeningCommanderDistance: 110,
  assassinTelegraphMs: 650,
  assassinDashSpeedMultiplier: 2.8,
  assassinEscapeDurationMs: 2200,
  assassinEscapeSpeedMultiplier: 1.6,
  siegeShellRadius: 55,
  siegePreferredRange: 240,
  bossSummonCooldownMs: 12_000,
  bossChargeCooldownMs: 10_000,
};

export const ENCOUNTER_PHASES: EncounterPhase[] = [
  {
    id: 'scout_probe',
    delayMs: 2500,
    announcement: 'Enemy scouts probing your flank',
    squads: [{ role: 'scout', count: 2 }],
  },
  {
    id: 'ranged_pressure',
    delayMs: 12_000,
    announcement: 'Archers deploying behind the line',
    squads: [
      { role: 'bruiser', count: 1 },
      { role: 'archer', count: 2 },
    ],
  },
  {
    id: 'assassin_test',
    delayMs: 22_000,
    announcement: 'Assassin circling — Support behind the line',
    squads: [
      { role: 'assassin', count: 1 },
      { role: 'support', count: 1 },
      { role: 'scout', count: 1 },
    ],
  },
  {
    id: 'siege_pressure',
    delayMs: 32_000,
    announcement: 'Siege battery targeting your command position',
    squads: [
      { role: 'siege', count: 1 },
      { role: 'bruiser', count: 1 },
      { role: 'archer', count: 1 },
    ],
  },
  {
    id: 'boss',
    delayMs: 40_000,
    announcement: 'Field Captain on the field',
    spawnBoss: true,
    squads: [
      { role: 'support', count: 1 },
      { role: 'assassin', count: 1 },
    ],
  },
];

export const ENCOUNTER_CONFIG = {
  spawnRadius: 400,
  maxAlive: 18,
  staggerSpawnMs: 350,
};
