/** Scaling cost for leveled investments: base * growth^level */
export function scaledCost(base, growth, level) {
  return Math.max(1, Math.round(base * Math.pow(growth, level)));
}

/** Run-wide global upgrades — affect all towers and economy for this run. */
export const GLOBAL_UPGRADES = {
  global_damage: {
    id: 'global_damage',
    name: 'Global Damage',
    description: '+5% damage to all towers',
    baseCost: 120,
    costGrowth: 1.38,
    maxLevel: 12,
    effectPerLevel: { damageMult: 0.05 },
  },
  global_attack_speed: {
    id: 'global_attack_speed',
    name: 'Attack Speed',
    description: '+5% attack speed',
    baseCost: 130,
    costGrowth: 1.38,
    maxLevel: 12,
    effectPerLevel: { attackSpeedMult: 0.05 },
  },
  global_range: {
    id: 'global_range',
    name: 'Global Range',
    description: '+5% tower range',
    baseCost: 110,
    costGrowth: 1.36,
    maxLevel: 12,
    effectPerLevel: { rangeMult: 0.05 },
  },
  global_crit: {
    id: 'global_crit',
    name: 'Critical Chance',
    description: '+5% critical hit chance',
    baseCost: 150,
    costGrowth: 1.4,
    maxLevel: 10,
    effectPerLevel: { critChance: 0.05 },
  },
  global_projectile_speed: {
    id: 'global_projectile_speed',
    name: 'Projectile Speed',
    description: '+5% projectile speed',
    baseCost: 100,
    costGrowth: 1.35,
    maxLevel: 10,
    effectPerLevel: { projectileSpeedMult: 0.05 },
  },
  global_sell_value: {
    id: 'global_sell_value',
    name: 'Sell Value',
    description: '+5% structure sell value',
    baseCost: 90,
    costGrowth: 1.34,
    maxLevel: 8,
    effectPerLevel: { sellValueMult: 0.05 },
  },
  global_farm_production: {
    id: 'global_farm_production',
    name: 'Farm Production',
    description: '+5% Sunpatch income',
    baseCost: 100,
    costGrowth: 1.36,
    maxLevel: 12,
    effectPerLevel: { farmIncomeMult: 0.05 },
  },
  global_crystal_rate: {
    id: 'global_crystal_rate',
    name: 'Crystal Drops',
    description: '+5% crystal generation',
    baseCost: 140,
    costGrowth: 1.4,
    maxLevel: 10,
    effectPerLevel: { crystalMult: 0.05 },
  },
  global_boss_rewards: {
    id: 'global_boss_rewards',
    name: 'Boss Rewards',
    description: '+5% boss kill gold',
    baseCost: 160,
    costGrowth: 1.42,
    maxLevel: 10,
    effectPerLevel: { bossRewardMult: 0.05 },
  },
  global_research_gen: {
    id: 'global_research_gen',
    name: 'Research Generation',
    description: '+5% Research Points per wave',
    baseCost: 125,
    costGrowth: 1.37,
    maxLevel: 10,
    effectPerLevel: { researchMult: 0.05 },
  },
};

/** No maximum level — costs scale forever. */
export const ENDLESS_INVESTMENTS = {
  endless_farm: {
    id: 'endless_farm',
    name: 'Farm Efficiency',
    description: '+3% farm income per level (no cap)',
    baseCost: 180,
    costGrowth: 1.42,
    effectPerLevel: { farmIncomeMult: 0.03 },
  },
  endless_damage: {
    id: 'endless_damage',
    name: 'Global Damage',
    description: '+3% tower damage per level (no cap)',
    baseCost: 200,
    costGrowth: 1.44,
    effectPerLevel: { damageMult: 0.03 },
  },
  endless_range: {
    id: 'endless_range',
    name: 'Tower Range',
    description: '+3% range per level (no cap)',
    baseCost: 175,
    costGrowth: 1.43,
    effectPerLevel: { rangeMult: 0.03 },
  },
  endless_gold: {
    id: 'endless_gold',
    name: 'Gold Multiplier',
    description: '+3% all gold earned per level (no cap)',
    baseCost: 220,
    costGrowth: 1.45,
    effectPerLevel: { goldEarnedMult: 0.03 },
  },
  endless_crystal: {
    id: 'endless_crystal',
    name: 'Crystal Multiplier',
    description: '+3% crystals per level (no cap)',
    baseCost: 240,
    costGrowth: 1.46,
    effectPerLevel: { crystalMult: 0.03 },
  },
  endless_research: {
    id: 'endless_research',
    name: 'Research Speed',
    description: '+3% RP generation per level (no cap)',
    baseCost: 190,
    costGrowth: 1.43,
    effectPerLevel: { researchMult: 0.03 },
  },
  endless_boss: {
    id: 'endless_boss',
    name: 'Boss Rewards',
    description: '+3% boss rewards per level (no cap)',
    baseCost: 260,
    costGrowth: 1.47,
    effectPerLevel: { bossRewardMult: 0.03 },
  },
};

/** One-wave commander buffs purchased before starting a wave. */
export const COMMANDER_ABILITIES = {
  rally_troops: {
    id: 'rally_troops',
    name: 'Rally Troops',
    description: '+20% tower damage this wave',
    cost: 85,
    effects: { damageMult: 0.2 },
  },
  rapid_reload: {
    id: 'rapid_reload',
    name: 'Rapid Reload',
    description: '+25% attack speed this wave',
    cost: 90,
    effects: { attackSpeedMult: 0.25 },
  },
  economic_boom: {
    id: 'economic_boom',
    name: 'Economic Boom',
    description: '+50% farm income this wave',
    cost: 75,
    effects: { farmIncomeMult: 0.5 },
  },
  crystal_infusion: {
    id: 'crystal_infusion',
    name: 'Crystal Infusion',
    description: '+25% crystal rewards this wave',
    cost: 100,
    effects: { crystalMult: 0.25 },
  },
  emergency_lives: {
    id: 'emergency_lives',
    name: 'Emergency Reinforcements',
    description: '+2 lives this wave (lost if unused)',
    cost: 120,
    effects: { bonusLives: 2 },
  },
  supply_drop: {
    id: 'supply_drop',
    name: 'Supply Drop',
    description: 'Instant +150 gold (costs 100g to call)',
    cost: 100,
    instantGold: 150,
    effects: {},
  },
  defensive_protocol: {
    id: 'defensive_protocol',
    name: 'Defensive Protocol',
    description: 'Repair all damaged structures now',
    cost: 60,
    repairAll: true,
    effects: {},
  },
};

/** Headquarters upgrades — permanent for the run. */
export const HQ_UPGRADES = {
  hq_starting_gold: {
    id: 'hq_starting_gold',
    name: 'Treasury Vault',
    description: '+40 starting gold (retroactive bonus gold)',
    baseCost: 150,
    costGrowth: 1.5,
    maxLevel: 6,
    effectPerLevel: { bonusGold: 40 },
  },
  hq_lives: {
    id: 'hq_lives',
    name: 'Reinforced Walls',
    description: '+2 max lives',
    baseCost: 200,
    costGrowth: 1.55,
    maxLevel: 5,
    effectPerLevel: { bonusLives: 2 },
  },
  hq_armor: {
    id: 'hq_armor',
    name: 'Base Armor',
    description: '+5% structure armor',
    baseCost: 175,
    costGrowth: 1.48,
    maxLevel: 6,
    effectPerLevel: { structureArmor: 0.05 },
  },
  hq_passive_gold: {
    id: 'hq_passive_gold',
    name: 'Passive Income',
    description: '+8 gold per wave',
    baseCost: 160,
    costGrowth: 1.45,
    maxLevel: 8,
    effectPerLevel: { passiveGoldPerWave: 8 },
  },
  hq_passive_repair: {
    id: 'hq_passive_repair',
    name: 'Passive Repairs',
    description: '+5 HP to all structures each wave',
    baseCost: 140,
    costGrowth: 1.42,
    maxLevel: 8,
    effectPerLevel: { passiveRepairPerWave: 5 },
  },
  hq_boss_rewards: {
    id: 'hq_boss_rewards',
    name: 'Boss Bounties',
    description: '+8% boss rewards',
    baseCost: 190,
    costGrowth: 1.5,
    maxLevel: 6,
    effectPerLevel: { bossRewardMult: 0.08 },
  },
  hq_reward_mult: {
    id: 'hq_reward_mult',
    name: 'Reward Multiplier',
    description: '+5% all wave rewards',
    baseCost: 210,
    costGrowth: 1.52,
    maxLevel: 6,
    effectPerLevel: { goldEarnedMult: 0.05 },
  },
};

/** Passive economy structure boosts. */
export const ECONOMIC_INVESTMENTS = {
  econ_farms: {
    id: 'econ_farms',
    name: 'Farm Networks',
    description: '+8% Sunpatch income',
    baseCost: 130,
    costGrowth: 1.4,
    maxLevel: 10,
    effectPerLevel: { farmIncomeMult: 0.08 },
  },
  econ_banks: {
    id: 'econ_banks',
    name: 'Banking Reform',
    description: '+10% bank interest',
    baseCost: 150,
    costGrowth: 1.42,
    maxLevel: 8,
    effectPerLevel: { bankInterestMult: 0.1 },
  },
  econ_marketplace: {
    id: 'econ_marketplace',
    name: 'Trade Routes',
    description: '+6% gold earned',
    baseCost: 140,
    costGrowth: 1.41,
    maxLevel: 10,
    effectPerLevel: { goldEarnedMult: 0.06 },
  },
  econ_research: {
    id: 'econ_research',
    name: 'Scholarly Funding',
    description: '+10% RP generation',
    baseCost: 160,
    costGrowth: 1.43,
    maxLevel: 8,
    effectPerLevel: { researchMult: 0.1 },
  },
  econ_crystals: {
    id: 'econ_crystals',
    name: 'Crystal Prospecting',
    description: '+12% crystal yield',
    baseCost: 180,
    costGrowth: 1.45,
    maxLevel: 8,
    effectPerLevel: { crystalMult: 0.12 },
  },
};

/** One wonder per run — endgame gold sink. */
export const WORLD_WONDERS = {
  golden_treasury: {
    id: 'golden_treasury',
    name: 'Golden Treasury',
    description: 'Double farm production and bank interest.',
    cost: 55000,
    unlockWave: 25,
    effects: { farmIncomeMult: 1.0, bankInterestMult: 1.0 },
  },
  arcane_nexus: {
    id: 'arcane_nexus',
    name: 'Arcane Nexus',
    description: 'Magic towers chain +2 targets; +25% spell damage.',
    cost: 60000,
    unlockWave: 25,
    effects: { chainCountAdd: 2, damageMult: 0.25, magicTowerBonus: true },
  },
  war_academy: {
    id: 'war_academy',
    name: 'War Academy',
    description: '2× mastery XP; +15% global attack speed.',
    cost: 58000,
    unlockWave: 28,
    effects: { masteryXpMult: 2.0, attackSpeedMult: 0.15 },
  },
  fortress_core: {
    id: 'fortress_core',
    name: 'Fortress Core',
    description: '+50% structure health; +10% armor; +15 passive repair/wave.',
    cost: 52000,
    unlockWave: 22,
    effects: { structureHealthMult: 0.5, structureArmor: 0.1, passiveRepairPerWave: 15 },
  },
  grand_marketplace: {
    id: 'grand_marketplace',
    name: 'Grand Marketplace',
    description: '+20% kill gold; double boss rewards; +30% crystals.',
    cost: 65000,
    unlockWave: 30,
    effects: { goldEarnedMult: 0.2, bossRewardMult: 1.0, crystalMult: 0.3 },
  },
  engineers_guild: {
    id: 'engineers_guild',
    name: "Engineer's Guild",
    description: '-12% upgrade costs; -20% repair costs.',
    cost: 50000,
    unlockWave: 20,
    effects: { upgradeCostMult: -0.12, repairCostMult: -0.2 },
  },
  temple_prosperity: {
    id: 'temple_prosperity',
    name: 'Temple of Prosperity',
    description: '+15% all economy; bonus 25g per farm each wave.',
    cost: 70000,
    unlockWave: 32,
    effects: { farmIncomeMult: 0.15, goldEarnedMult: 0.15, farmBonusGold: 25 },
  },
};

/** Tower overclock — temporary per-tower buff for several waves. */
export const TOWER_OVERCLOCKS = {
  damage: {
    id: 'damage',
    name: 'Damage Overclock',
    description: '+40% damage for 3 waves',
    cost: 95,
    waves: 3,
    effects: { damageMult: 0.4 },
  },
  speed: {
    id: 'speed',
    name: 'Speed Overclock',
    description: '+35% attack speed for 3 waves',
    cost: 90,
    waves: 3,
    effects: { attackSpeedMult: 0.35 },
  },
  range: {
    id: 'range',
    name: 'Range Overclock',
    description: '+30% range for 3 waves',
    cost: 85,
    waves: 3,
    effects: { rangeMult: 0.3 },
  },
  projectile: {
    id: 'projectile',
    name: 'Velocity Overclock',
    description: '+50% projectile speed for 3 waves',
    cost: 75,
    waves: 3,
    effects: { projectileSpeedMult: 0.5 },
  },
  splash: {
    id: 'splash',
    name: 'Blast Overclock',
    description: '+60% splash radius for 3 waves',
    cost: 110,
    waves: 3,
    effects: { splashRadiusMult: 0.6 },
  },
};

/** Permanent structure reinforcement for the run (per structure). */
export const STRUCTURE_REINFORCEMENTS = {
  health: {
    id: 'health',
    name: 'Reinforced Hull',
    description: '+20% max health',
    baseCost: 70,
    costGrowth: 1.35,
    maxLevel: 6,
    effectPerLevel: { healthMult: 0.2 },
  },
  armor: {
    id: 'armor',
    name: 'Armor Plating',
    description: '+8% damage reduction',
    baseCost: 80,
    costGrowth: 1.38,
    maxLevel: 5,
    effectPerLevel: { armorAdd: 0.08 },
  },
  repair_rate: {
    id: 'repair_rate',
    name: 'Auto-Repair',
    description: '+3 HP repaired passively each wave',
    baseCost: 65,
    costGrowth: 1.32,
    maxLevel: 6,
    effectPerLevel: { passiveRepair: 3 },
  },
  repair_cost: {
    id: 'repair_cost',
    name: 'Efficient Repairs',
    description: '-10% manual repair cost',
    baseCost: 55,
    costGrowth: 1.3,
    maxLevel: 5,
    effectPerLevel: { repairCostMult: -0.1 },
  },
};

export const BUILD_EXPANSION = {
  baseCost: 250,
  costGrowth: 1.55,
  maxPurchases: 18,
};

export const INVESTMENT_CATEGORY_ORDER = [
  'commander',
  'global',
  'endless',
  'hq',
  'economy',
  'wonder',
  'expansion',
];
