/** Legendary tower upgrades — expensive wave-gated capstones that change behavior. */
export const LEGENDARY_UNLOCK_WAVE = 20;

export const LEGENDARY_UPGRADES = {
  needle: {
    id: 'needle_legendary',
    towerType: 'needle',
    name: 'Arrow Storm',
    description: 'Fires 2 darts per volley; each can Expose and chain once.',
    cost: 1200,
    effects: { projectileCount: 2, chainCount: 1, chainDamageMult: 0.55, exposedChance: 0.1 },
  },
  boulder: {
    id: 'boulder_legendary',
    towerType: 'boulder',
    name: 'Inferno Cannon',
    description: 'Massive explosions leave burning ground for 4s.',
    cost: 1400,
    effects: {
      damageMult: 1.5,
      splashRadiusMult: 1.8,
      burnDPS: 12,
      burnDuration: 4,
      groundBurn: true,
    },
  },
  prism: {
    id: 'prism_legendary',
    towerType: 'prism',
    name: 'Chain Lightning',
    description: 'Arcane bolts chain through 5 enemies.',
    cost: 1300,
    effects: { chainCount: 5, damageMult: 1.25, projectileSpeedMult: 1.3 },
  },
  gust: {
    id: 'gust_legendary',
    towerType: 'gust',
    name: 'Blizzard Aura',
    description: 'Freezes foes (70% slow) in range; aura radius +40%.',
    cost: 1250,
    effects: { auraSlow: 0.7, rangeMult: 1.4, damageMult: 1.2 },
  },
  ember: {
    id: 'ember_legendary',
    towerType: 'ember',
    name: 'Meteor Hearth',
    description: 'Burns ignore armor and spread to all nearby foes.',
    cost: 1350,
    effects: {
      burnDPS: 10,
      burnDuration: 5,
      burnIgnoresArmor: 1,
      burnSpread: 1,
      burnSpreadCount: 6,
      damageMult: 1.3,
    },
  },
  thorn: {
    id: 'thorn_legendary',
    towerType: 'thorn',
    name: 'Titanbane Ballista',
    description: 'Pierces all armor; +80% boss damage and +60% elite damage.',
    cost: 1450,
    effects: {
      armorPen: 0.35,
      pierce: 4,
      bossDamageMult: 1.8,
      eliteDamageMult: 1.6,
      damageMult: 1.35,
      critChance: 0.15,
    },
  },
  frost: {
    id: 'frost_legendary',
    towerType: 'frost',
    name: 'Glacial Heart',
    description: 'Near-freeze aura; pulse slow doubled in range.',
    cost: 1280,
    effects: {
      auraSlow: 0.62,
      rangeMult: 1.45,
      frostPulseSlow: 0.85,
      frostPulseInterval: 7,
      frostPulseDuration: 3.2,
      slowPercent: 0.7,
      slowDuration: 4,
    },
  },
};
