/** Run-wide research upgrades purchased with Research Points. */
export const RESEARCH_UPGRADES = {
  sharpened_blades: {
    id: 'sharpened_blades',
    name: 'Sharpened Blades',
    description: '+8% tower damage',
    cost: 12,
    maxLevel: 5,
    effects: { damageMult: 0.08 },
  },
  extended_reach: {
    id: 'extended_reach',
    name: 'Extended Reach',
    description: '+6% tower range',
    cost: 10,
    maxLevel: 5,
    effects: { rangeMult: 0.06 },
  },
  rapid_training: {
    id: 'rapid_training',
    name: 'Rapid Training',
    description: '+5% attack speed',
    cost: 14,
    maxLevel: 4,
    effects: { attackSpeedMult: 0.05 },
  },
  fertile_fields: {
    id: 'fertile_fields',
    name: 'Fertile Fields',
    description: '+10% farm production',
    cost: 10,
    maxLevel: 5,
    effects: { farmIncomeMult: 0.1 },
  },
  efficient_crafting: {
    id: 'efficient_crafting',
    name: 'Efficient Crafting',
    description: '-5% tower build cost',
    cost: 15,
    maxLevel: 4,
    effects: { buildCostMult: -0.05 },
  },
  golden_harvest: {
    id: 'golden_harvest',
    name: 'Golden Harvest',
    description: '+15 starting gold',
    cost: 8,
    maxLevel: 3,
    effects: { bonusStartingGold: 15 },
  },
  salvage_expert: {
    id: 'salvage_expert',
    name: 'Salvage Expert',
    description: '+20% sell value',
    cost: 12,
    maxLevel: 3,
    effects: { sellValueMult: 0.2 },
  },
  boss_bounty: {
    id: 'boss_bounty',
    name: 'Boss Bounty',
    description: '+25% boss kill rewards',
    cost: 20,
    maxLevel: 3,
    effects: { bossRewardMult: 0.25 },
  },
};
