/** Tower type definitions — add new towers here without touching core logic. */
export const TOWER_TYPES = {
  needle: {
    id: 'needle',
    name: 'Needle Post',
    description: 'Precision darts — specialize into rapid fire, marksman, or hunter paths.',
    cost: 40,
    category: 'military',
    color: '#3d9970',
    icon: '△',
    baseStats: {
      damage: 9,
      range: 3.6,
      attackSpeed: 1.3,
    },
    projectileColor: '#2ecc71',
    projectileSpeed: 13,
  },

  boulder: {
    id: 'boulder',
    name: 'Boulder Pit',
    description: 'Slow, heavy shots that splash nearby foes.',
    cost: 70,
    category: 'military',
    color: '#c0392b',
    icon: '◆',
    baseStats: {
      damage: 28,
      range: 2.9,
      attackSpeed: 0.45,
      splashRadius: 1.3,
    },
    projectileColor: '#922b21',
    projectileSpeed: 9,
  },

  prism: {
    id: 'prism',
    name: 'Prism Spire',
    description: 'Long reach and steady arcane damage.',
    cost: 55,
    category: 'magic',
    magicTowerBonus: true,
    color: '#6c5ce7',
    icon: '◇',
    baseStats: {
      damage: 15,
      range: 4.8,
      attackSpeed: 0.85,
    },
    projectileColor: '#a29bfe',
    projectileSpeed: 11,
  },

  gust: {
    id: 'gust',
    name: 'Gust Totem',
    description: 'Slows foes in range; upgrades add knockback.',
    cost: 58,
    unlockWave: 15,
    unlockFlag: 'gust_from_wave_1',
    unlockFlagMinWave: 1,
    category: 'magic',
    color: '#4db6ac',
    icon: '◎',
    baseStats: {
      damage: 6,
      range: 3.4,
      attackSpeed: 0.55,
      auraSlow: 0.22,
    },
    projectileColor: '#80cbc4',
    projectileSpeed: 10,
    isAuraTower: true,
  },

  ember: {
    id: 'ember',
    name: 'Ember Hearth',
    description: 'Burns enemies over time — strong vs armored foes.',
    cost: 62,
    unlockWave: 25,
    unlockFlag: 'ember_early',
    unlockFlagBypassWave: true,
    color: '#e65100',
    icon: '✧',
    baseStats: {
      damage: 11,
      range: 3.1,
      attackSpeed: 0.75,
      burnDPS: 5,
      burnDuration: 3,
    },
    projectileColor: '#ff7043',
    projectileSpeed: 10,
  },

  thorn: {
    id: 'thorn',
    name: 'Thorn Launcher',
    description: 'Armor-piercing bolts — excels vs elites and bosses, weak vs swarms.',
    cost: 76,
    unlockWave: 18,
    category: 'military',
    color: '#558b2f',
    icon: '✦',
    baseStats: {
      damage: 24,
      range: 4.2,
      attackSpeed: 0.38,
      armorPen: 0.28,
      bossDamageMult: 1.4,
      eliteDamageMult: 1.3,
    },
    projectileColor: '#7cb342',
    projectileSpeed: 11,
  },

  frost: {
    id: 'frost',
    name: 'Frost Spire',
    description: 'Strong chill aura and slowing shots — low damage, elite crowd control.',
    cost: 58,
    unlockWave: 20,
    category: 'magic',
    color: '#29b6f6',
    icon: '❄',
    baseStats: {
      damage: 5,
      range: 3.3,
      attackSpeed: 0.52,
      auraSlow: 0.32,
      slowPercent: 0.38,
      slowDuration: 2.2,
    },
    projectileColor: '#81d4fa',
    projectileSpeed: 9,
    isAuraTower: true,
  },
};
